set_program:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: solem_blip
    program:
      required: true
      selector:
        select:
          options:
          - '1'
          - '2'
          - '3'
    name:
      selector:
        text: null
    cycle:
      selector:
        select:
          options:
          - custom
          - even
          - odd
          - odd_31
          - periodic
    week_days:
      selector:
        select:
          multiple: true
          options:
          - monday
          - tuesday
          - wednesday
          - thursday
          - friday
          - saturday
          - sunday
    period_length:
      selector:
        number:
          min: 1
          max: 255
          mode: box
    synchro_day:
      selector:
        number:
          min: 0
          max: 255
          mode: box
    period_start_date:
      selector:
        date: null
    start_times:
      selector:
        object: null
    station_durations:
      selector:
        object: null
    inter_station_delay:
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    water_budget:
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    revision:
      required: true
      selector:
        text: null
refresh_programs:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: solem_blip
accept_current_programs:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: solem_blip
apply_rainfall:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: solem_blip
